development:
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
test:
  auth0_domain:
  auth0_client_id:
  auth0_client_secret:
production:
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
